(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(blink-cursor-mode nil)
 '(column-number-mode t)
 '(completions-format (quote vertical))
 '(custom-safe-themes (quote ("6b076aec76f8e203ec05ca6ac05564c6e2594adc" "171e4911e28356ec77a6fc2e5706eea9724c9b5f" default)))
 '(fringe-mode (quote (4 . 4)) nil (fringe))
 '(global-hl-line-mode nil)
 '(global-pretty-lambda-mode t)
 '(ido-enable-dot-prefix t)
 '(ido-enable-prefix t)
 '(ido-everywhere t)
 '(ido-record-ftp-work-directories nil)
 '(indicate-empty-lines t)
 '(inhibit-startup-echo-area-message "endymion")
 '(initial-scratch-message nil)
 '(kill-do-not-save-duplicates t)
 '(mouse-avoidance-mode (quote banish) nil (avoid))
 '(prelude-disable-arrow-navigation nil)
 '(read-buffer-completion-ignore-case t)
 '(read-file-name-completion-ignore-case t)
 '(require-final-newline t)
 '(ruby-block-highlight-toggle t)
 '(show-paren-mode t)
 '(show-paren-style (quote parenthesis))
 '(size-indication-mode t)
 '(tool-bar-mode nil)
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(whitespace-action (quote (auto-cleanup warn-if-read-only)))
 '(whitespace-display-mappings nil)
 '(whitespace-style (quote (trailing empty)))
 '(windmove-wrap-around t)
 '(xterm-mouse-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "#0b0b0b" :foreground "#92b6f4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 87 :width normal :foundry "xos4" :family "Terminus"))))
 '(c-annotation-face ((t (:foreground "steel blue"))) t)
 '(cursor ((t nil)))
 '(fixed-pitch ((t (:family "Terminus"))))
 '(font-lock-builtin-face ((t (:foreground "#a4e0a7"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#ff0000"))))
 '(font-lock-comment-face ((t (:foreground "#dd3333"))))
 '(font-lock-constant-face ((t (:foreground "#a47bff"))))
 '(font-lock-function-name-face ((t (:foreground "#0674ff" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#66d6ff" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#ccaaff" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#6c60ff" :weight ultra-bold))))
 '(font-lock-regexp-grouping-backslash ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#eb9366"))))
 '(font-lock-type-face ((t (:foreground "#99ee99" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#f0dfaf"))))
 '(font-lock-warning-face ((t (:background "#332323" :foreground "#e37170"))))
 '(fringe ((t (:background "grey20"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box (:line-width -1 :color "#5276b4")))))
 '(highlight ((t (:background "#115544"))))
 '(ido-first-match ((t (:weight bold))))
 '(ido-only-match ((t (:foreground "ForestGreen"))))
 '(ido-subdir ((t (:foreground "red1"))))
 '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
 '(isearch-fail ((t (:background "red4"))))
 '(italic ((t (:slant italic))))
 '(lazy-highlight ((t (:background "#335544"))))
 '(link ((t (:foreground "cyan1" :underline t))))
 '(link-visited ((t (:foreground "violet" :underline t))))
 '(match ((t (:background "#3344bb"))))
 '(menu ((t nil)))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(mode-line ((t (:background "#131313" :foreground "#a47bff" :box (:line-width -1 :color "#5276b4")))))
 '(mode-line-buffer-id ((t (:foreground "#30ddff" :weight normal))))
 '(mode-line-emphasis ((t (:foreground "#c460ff" :weight bold))))
 '(mode-line-highlight ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style released-button)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style released-button) :weight light))))
 '(next-error ((t (:background "#441133"))))
 '(secondary-selection ((t (:background "#334433"))))
 '(show-paren-match ((t (:background "#b2a6f4" :foreground "#000000" :weight extra-bold))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(trailing-whitespace ((t (:background "firebrick"))))
 '(variable-pitch ((t (:family "Ubuntu"))))
 '(vertical-border ((t nil)))
 '(whitespace-empty ((t (:background "#2e2533"))))
 '(whitespace-hspace ((t nil)))
 '(whitespace-indentation ((t nil)))
 '(whitespace-line ((t (:background "#151012" :foreground "#bc7cb3"))))
 '(whitespace-newline ((t nil)))
 '(whitespace-space ((t (:background "#0b0b0b"))))
 '(whitespace-tab ((t nil)))
 '(whitespace-trailing ((t (:background "firebrick3" :foreground "thistle2"))))
 '(widget-button ((t (:background "#92b6f4" :foreground "black" :box (:line-width 2 :color "#92b6f4" :style released-button) :weight bold))))
 '(widget-button-pressed ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style pressed-button)))))
 '(widget-field ((t (:background "#333333"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "#333333")))))
