(deftheme pdklburn2
  "Created 2012-01-10.")

(custom-theme-set-variables
 'pdklburn2)

(custom-theme-set-faces
 'pdklburn2

 ;; inherited from pdklburn
 '(whitespace-empty ((t (:background "#2e2533"))))
 '(whitespace-hspace ((t nil)))
 '(whitespace-indentation ((t nil)))
 '(whitespace-line ((t (:background "#151012" :foreground "#bc7cb3"))))
 '(whitespace-newline ((t nil)))
 '(whitespace-space ((t (:background "#0b0b0b"))))
 '(whitespace-tab ((t nil)))
 '(whitespace-trailing ((t (:background "firebrick3" :foreground "thistle2"))))
 '(c-annotation-face ((t (:foreground "steel blue"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#ff0000"))))
 '(font-lock-comment-face ((t (:foreground "#dd3333"))))
 '(font-lock-constant-face ((t (:foreground "#a47bff"))))
 '(font-lock-preprocessor-face ((t (:foreground "#6c60ff" :weight ultra-bold))))
 '(font-lock-regexp-grouping-backslash ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#eb9366"))))
 '(font-lock-type-face ((t (:foreground "#99ee99" :weight bold))))
 '(fringe ((t (:background "grey20"))))
 '(widget-button ((t (:background "#92b6f4" :foreground "black" :box (:line-width 2 :color "#92b6f4" :style released-button) :weight bold))))
 '(widget-button-pressed ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style pressed-button)))))
 '(widget-field ((t (:background "#333333"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "#333333"))))
 '(vertical-border ((t nil)))
 '(variable-pitch ((t (:family "Ubuntu"))))
 '(trailing-whitespace ((t (:background "firebrick"))))
 '(secondary-selection ((t (:background "#334433"))))
 '(next-error ((t (:background "#441133"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style released-button) :weight light))))
 '(mode-line-highlight ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style released-button)))))
 '(mode-line-emphasis ((t (:foreground "#c460ff" :weight bold))))
 '(mode-line-buffer-id ((t (:foreground "#30ddff" :weight normal))))
 '(mode-line ((t (:background "#131313" :foreground "#a47bff" :box (:line-width -1 :color "#5276b4")))))
 '(menu ((t nil)))
 '(match ((t (:background "#3344bb"))))
 '(link-visited ((t (:foreground "violet" :underline t))))
 '(link ((t (:foreground "cyan1" :underline t))))
 '(lazy-highlight ((t (:background "#335544"))))
 '(italic ((t (:slant italic))))
 '(isearch-fail ((t (:background "red4"))))
 '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
 '(ido-subdir ((t (:foreground "red1"))))
 '(ido-first-match ((t (:weight bold))))
 '(highlight ((t (:background "#115544"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box (:line-width -1 :color "#5276b4")))))
 '(fixed-pitch ((t (:family "Terminus"))))


 ;; new in pdklburn2
 '(css-proprietary-property ((t (:inherit css-property :background "#171005"))))
 '(css-selector ((t (:inherit font-lock-builtin-face))))
 '(cursor ((t (:background "#ADA8F2"))))
 '(dropdown-list-face ((t (:inherit modeline))))
 '(dropdown-list-selection-face ((t (:inherit modeline-highlight))))
 '(error ((t (:background "#6b0a1e" :foreground "#ffeefb" :underline "#ff3111" :weight bold))))
 '(escape-glyph ((t (:background "DodgerBlue4" :foreground "#B4B1FF" :box (:line-width 1 :color "light slate blue")))))
 '(flymake-errline ((t (:background "Firebrick4" :underline "firebrick"))))
 '(flyspell-incorrect ((t (:foreground "OrangeRed" :underline nil :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "light green"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :background "#2a0a0a" :foreground "#ff0000"))))
 '(font-lock-comment-face ((t (:foreground "#f23331"))))
 '(font-lock-function-name-face ((t (:foreground "#3156ff" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#24ddee" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "maroon1" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "wheat"))))
 '(font-lock-warning-face ((t (:inherit error :background "#510715" :foreground "#fcefeb" :underline "#ff3516"))))
 '(highlight ((t (:background "RoyalBlue4"))))
 '(hl-line ((t (:background "black"))))
 '(ido-only-match ((t (:inherit font-lock-keyword-face :foreground "#24ddee"))))
 '(isearch ((t (:background "plum" :foreground "#5b1313"))))
 '(js2-error ((t (:inherit font-lock-warning-face :foreground "#fcefeb"))))
 '(js2-external-variable ((t (:inherit sh-quoted-exec :foreground "IndianRed1"))))
 '(js2-function-param ((t (:foreground "SpringGreen3"))))
 '(js2-instance-member ((t (:inherit font-lock-constant-face :foreground "#a47bff"))))
 '(js2-magic-paren ((t (:inherit font-lock-preprocessor-face))))
 '(js2-warning ((t (:underline "#ffca10"))))
 '(link ((t (:inherit font-lock-function-name-face))))
 '(minibuffer-prompt ((t (:inherit font-lock-keyword-face))))
 '(outline-1 ((t (:inherit rainbow-delimiters-depth-1-face))))
 '(outline-2 ((t (:inherit rainbow-delimiters-depth-2-face))))
 '(outline-3 ((t (:inherit rainbow-delimiters-depth-3-face))))
 '(outline-4 ((t (:inherit rainbow-delimiters-depth-4-face))))
 '(outline-5 ((t (:inherit rainbow-delimiters-depth-5-face))))
 '(outline-6 ((t (:inherit rainbow-delimiters-depth-6-face))))
 '(outline-7 ((t (:inherit rainbow-delimiters-depth-7-face))))
 '(outline-8 ((t (:inherit rainbow-delimiters-depth-8-face))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "deep sky blue"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "light slate blue"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "dodger blue"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#00ca8a"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "yellow green"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "DarkGoldenrod2"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "firebrick2"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "magenta2"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "DeepSkyBlue2"))))
 '(rainbow-delimiters-unmatched-face ((t (:background "#001a16" :foreground "SpringGreen2"))))
 '(region ((t (:background "#1d182e"))))
 '(sh-heredoc ((t (:background "dark slate blue" :foreground "CadetBlue1"))))
 '(sh-quoted-exec ((t (:foreground "IndianRed1"))))
 '(show-paren-match ((t (:background "dark slate blue" :foreground "light cyan"))))
 '(show-paren-mismatch ((t (:background "blue violet" :foreground "white smoke" :strike-through "red"))))
 '(strokes-char ((t (:background "black"))))
 '(tool-bar ((t (:inherit modeline :background "#131313" :foreground "#a47bff" :box (:line-width -1 :color "#5276b4")))))
 '(tooltip ((t (:inherit modeline :background "#131313" :foreground "#a47bff"))))
 '(variable-pitch ((t (:stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1.0 :width normal :foundry "bitstream" :family "bitstream vera sans"))))
 '(default ((t (:inherit nil :stipple nil :background "#0b0b0b" :foreground "#92b6f4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 130 :width normal :foundry "microsoft" :family "Consolas")))))

(provide-theme 'pdklburn2)
