;;
;;        /\          /\          /\
;;     /\//\\/\    /\//\\/\    /\//\\/\
;;  /\//\\\///\\/\//\\\///\\/\//\\\///\\/\
;; //\\\//\/\\///\\\//\/\\///\\\//\/\\///\\
;; \\//\/                            \/\\//
;;  \/     pdkl95-colorful-clarity      \/
;;  /\     -----------------------      /\
;; //\\                                //\\
;; \\//   A custom-theme with bright   \\//
;;  \/   colors, that maintains both    \/
;;  /\      constrast and clarity.      /\
;; //\\/\                            /\//\\
;; \\///\\/\//\\\///\\/\//\\\///\\/\//\\\//
;;  \/\\///\\\//\/\\///\\\//\/\\///\\\//\/
;;     \/\\//\/    \/\\//\/    \/\\//\/
;;        \/          \/          \/
;;
;;  created: 2012-01-10
;;  updated: 2012-04-23
;;  updated: 2012-08-10
;;


(deftheme pdklburn
  "A custom-thtme with bright colors,
 that maintains both contrast and clarity.")

(custom-theme-set-variables
 'pdklburn)

(custom-theme-set-faces
 'pdklburn

 '(c-annotation-face ((t (:foreground "steel blue"))))
 '(css-proprietary-property ((t (:inherit css-property :background "#171005"))))
 '(css-selector ((t (:inherit font-lock-builtin-face))))
 '(cursor ((t (:background "#ADA8F2"))))
 '(default ((t (:inherit nil :stipple nil :background "#0b0b0b" :foreground "#92b6f4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 116 :width normal :foundry "unknown" :family "Dina"))))
 '(dropdown-list-face ((t (:inherit modeline))))
 '(dropdown-list-selection-face ((t (:inherit modeline-highlight))))
 '(erm-syn-errline ((t (:box nil :strike-through "firebrick1" :underline "red"))))
 '(erm-syn-warnline ((t (:box nil :strike-through "gold" :underline "orange"))))
 '(error ((t (:background "#6b0a1e" :foreground "#ffeefb" :underline "#ff3111" :weight bold))))
 '(escape-glyph ((t (:background "DodgerBlue4" :foreground "#B4B1FF" :box (:line-width 1 :color "light slate blue")))))
 '(fixed-pitch ((t (:family "Terminus"))))
 '(flymake-errline ((t (:background "#30160c" :underline "firebrick"))))
 '(flyspell-incorrect ((t (:foreground "OrangeRed" :underline nil :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "light green"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :background "#2a0a0a" :foreground "#ff0000"))))
 '(font-lock-comment-face ((t (:foreground "#f23331"))))
 '(font-lock-constant-face ((t (:foreground "#a47bff"))))
 '(font-lock-doc-face ((t (:background "#1e1927" :foreground "brown2"))))
 '(font-lock-function-name-face ((t (:foreground "#2266ff" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#00f4ff"))))
 '(font-lock-negation-char-face ((t (:foreground "maroon1" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#6c60ff" :weight ultra-bold))))
 '(font-lock-regexp-grouping-backslash ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#eb9366"))))
 '(font-lock-type-face ((t (:foreground "#99ee99" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "wheat"))))
 '(font-lock-warning-face ((t (:inherit error :background "#510715" :foreground "#fcefeb" :underline "#ff3516"))))
 '(fringe ((t (:background "grey20"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box (:line-width -1 :color "#5276b4")))))
 '(highlight ((t (:background "RoyalBlue4"))))
 '(hl-line ((t (:background "black"))))
 '(ido-first-match ((t (:weight bold))))
 '(ido-only-match ((t (:inherit font-lock-keyword-face :foreground "#24ddee"))))
 '(ido-subdir ((t (:foreground "RoyalBlue2" :weight bold))))
 '(isearch ((t (:background "plum" :foreground "#5b1313"))))
 '(isearch-fail ((t (:background "red4"))))
 '(italic ((t (:slant italic))))
 '(jabber-activity-face ((t (:background "salmon" :foreground "gray5" :box (:line-width 2 :color "SteelBlue3" :style pressed-button) :weight bold))))
 '(jabber-activity-personal-face ((t (:background "black" :foreground "lime green" :box (:line-width 1 :color "forest green")))))
 '(jabber-chat-error ((t (:background "dark red" :foreground "light goldenrod yellow" :weight normal))))
 '(jabber-chat-prompt-foreign ((t (:foreground "firebrick" :slant normal :weight bold))))
 '(jabber-chat-prompt-local ((t (:foreground "RoyalBlue3" :weight bold))))
 '(jabber-chat-prompt-system ((t (:foreground "MediumPurple2" :weight bold))))
 '(jabber-chat-text-foreign ((t (:background "gray12" :foreground "LavenderBlush1"))))
 '(jabber-chat-text-local ((t (:background "gray0" :foreground "green3"))))
 '(jabber-rare-time-face ((t (:foreground "DarkGoldenrod3" :underline t))))
 '(jabber-roster-user-away ((t (:foreground "slate blue" :slant normal :weight normal))))
 '(jabber-roster-user-chatty ((t (:foreground "chartreuse" :slant normal :weight bold))))
 '(jabber-roster-user-dnd ((t (:foreground "red4" :slant normal :weight normal))))
 '(jabber-roster-user-error ((t (:background "firebrick" :foreground "thistle" :slant italic :weight light))))
 '(jabber-roster-user-offline ((t (:foreground "dim gray" :slant normal :weight normal))))
 '(jabber-roster-user-online ((t (:foreground "SeaGreen1" :slant normal :weight bold))))
 '(jabber-roster-user-xa ((t (:foreground "dark violet" :slant normal :weight normal))))
 '(jabber-title-large ((t (:inherit variable-pitch :background "dark slate blue" :foreground "white" :box (:line-width 1 :color "royal blue") :weight normal :height 3.0 :family "Kelly Slab"))))
 '(jabber-title-medium ((t (:inherit variable-pitch :background "SlateBlue4" :foreground "honeydew" :weight bold :height 2.0 :width normal :family "Primer"))))
 '(jabber-title-small ((t (:background "dark slate blue" :foreground "CadetBlue1" :box (:line-width 2 :color "purple4" :style pressed-button) :family "peep"))))
 '(js2-error ((t (:inherit font-lock-warning-face :foreground "#fcefeb"))))
 '(js2-external-variable ((t (:inherit sh-quoted-exec :foreground "IndianRed1"))))
 '(js2-function-param ((t (:foreground "SpringGreen3"))))
 '(js2-instance-member ((t (:inherit font-lock-constant-face :foreground "#a47bff"))))
 '(js2-magic-paren ((t (:inherit font-lock-preprocessor-face))))
 '(js2-warning ((t (:underline "#ffca10"))))
 '(js3-error ((t (:inherit font-lock-warning-face :foreground "#fcefeb"))))
 '(js3-external-variable ((t (:inherit sh-quoted-exec :foreground "IndianRed1"))))
 '(js3-function-param ((t (:foreground "SpringGreen3"))))
 '(js3-instance-member ((t (:inherit font-lock-constant-face :foreground "#a47bff"))))
 '(js3-magic-paren ((t (:inherit font-lock-preprocessor-face))))
 '(js3-warning ((t (:underline "#ffca10"))))
 '(lazy-highlight ((t (:background "#335544"))))
 '(link ((t (:foreground "#2277ff" :weight normal :underline t))))
 '(link-visited ((t (:inherit link :foreground "#6255ff"))))
 '(match ((t (:background "#3344bb"))))
 '(menu ((t nil)))
 '(minibuffer-prompt ((t (:inherit font-lock-keyword-face))))
 '(mode-line ((t (:background "#131313" :foreground "#a47bff" :box (:line-width -1 :color "#5276b4")))))
 '(mode-line-buffer-id ((t (:foreground "#30ddff" :weight normal))))
 '(mode-line-emphasis ((t (:foreground "#c460ff" :weight bold))))
 '(mode-line-highlight ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style released-button)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style released-button) :weight light))))
 '(mumamo-background-chunk-major ((t (:background "#0d0b1d"))))
 '(mumamo-background-chunk-submode1 ((t (:background "#002448"))))
 '(mumamo-background-chunk-submode2 ((t (:background "#0d4c38"))))
 '(mumamo-background-chunk-submode3 ((t (:background "#44400F"))))
 '(mumamo-background-chunk-submode4 ((t (:background "#3E1D0A"))))
 '(mumamo-region ((t (:background "#00363b"))))
 '(next-error ((t (:background "#441133"))))
 '(nxml-tag-delimiter ((t (:inherit font-lock-constant-face))))
 '(nxml-tag-slash ((t (:foreground "SlateBlue"))))
 '(outline-1 ((t (:inherit rainbow-delimiters-depth-1-face))))
 '(outline-2 ((t (:inherit rainbow-delimiters-depth-2-face))))
 '(outline-3 ((t (:inherit rainbow-delimiters-depth-3-face))))
 '(outline-4 ((t (:inherit rainbow-delimiters-depth-4-face))))
 '(outline-5 ((t (:inherit rainbow-delimiters-depth-5-face))))
 '(outline-6 ((t (:inherit rainbow-delimiters-depth-6-face))))
 '(outline-7 ((t (:inherit rainbow-delimiters-depth-7-face))))
 '(outline-8 ((t (:inherit rainbow-delimiters-depth-8-face))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "deep sky blue"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "light slate blue"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "dodger blue"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#00ca8a"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "yellow green"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "DarkGoldenrod2"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "firebrick2"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "magenta2"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "DeepSkyBlue2"))))
 '(rainbow-delimiters-unmatched-face ((t (:background "#001a16" :foreground "SpringGreen2"))))
 '(region ((t (:background "#1f1836"))))
 '(ruby-op-face ((t (:background "#27132b" :foreground "#91a0ff" :weight semi-bold))))
 '(secondary-selection ((t (:background "#334433"))))
 '(sh-heredoc ((t (:background "dark slate blue" :foreground "CadetBlue1"))))
 '(sh-quoted-exec ((t (:foreground "IndianRed1"))))
 '(show-paren-match ((t (:background "dark slate blue" :foreground "light cyan"))))
 '(show-paren-mismatch ((t (:background "blue violet" :foreground "white smoke" :strike-through "red"))))
 '(strokes-char ((t (:background "black"))))
 '(tool-bar ((t (:inherit modeline :background "#131313" :foreground "#a47bff" :box (:line-width -1 :color "#5276b4")))))
 '(tooltip ((t (:inherit modeline :background "#131313" :foreground "#a47bff"))))
 '(trailing-whitespace ((t (:background "firebrick"))))
 '(variable-pitch ((t (:inherit default :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight thin :height 92 :width normal :foundry "unknown" :family "ubuntu"))))
 '(vertical-border ((t nil)))
 '(vhl/default-face ((t (:background "#2e134d"))))
 '(which-func ((t (:foreground "#45f"))))
 '(whitespace-empty ((t (:background "#2e2533"))))
 '(whitespace-hspace ((t nil)))
 '(whitespace-indentation ((t nil)))
 '(whitespace-line ((t (:background "#151012" :foreground "#bc7cb3"))))
 '(whitespace-newline ((t nil)))
 '(whitespace-space ((t (:background "#0b0b0b"))))
 '(whitespace-tab ((t nil)))
 '(whitespace-trailing ((t (:background "firebrick3" :foreground "thistle2"))))
 '(widget-button ((t (:background "#92b6f4" :foreground "black" :box (:line-width 2 :color "#92b6f4" :style released-button) :weight bold))))
 '(widget-button-pressed ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style pressed-button)))))
 '(widget-field ((t (:background "#333333"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "#333333"))))
)

(provide-theme 'pdklburn)
