(deftheme pdklburn
  "Created 2011-11-19.")

(custom-theme-set-variables
 'pdklburn
 )

(custom-theme-set-faces
 'pdklburn
 '(whitespace-empty ((t (:background "#2e2533"))))
 '(whitespace-hspace ((t nil)))
 '(whitespace-indentation ((t nil)))
 '(whitespace-line ((t (:background "#151012" :foreground "#bc7cb3"))))
 '(whitespace-newline ((t nil)))
 '(whitespace-space ((t (:background "#0b0b0b"))))
 '(whitespace-tab ((t nil)))
 '(whitespace-trailing ((t (:background "firebrick3" :foreground "thistle2"))))
 '(default ((t (:stipple nil :background "#0b0b0b" :foreground "#92b6f4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 87 :width normal :foundry "xos4" :family "Terminus"))))
 '(c-annotation-face ((t (:foreground "steel blue"))))
 '(font-lock-builtin-face ((t (:foreground "#a4e0a7"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#ff0000"))))
 '(font-lock-comment-face ((t (:foreground "#dd3333"))))
 '(font-lock-constant-face ((t (:foreground "#a47bff"))))
 '(font-lock-function-name-face ((t (:foreground "#0674ff" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#66d6ff" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#ccaaff" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#6c60ff" :weight ultra-bold))))
 '(font-lock-regexp-grouping-backslash ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:background "#333011" :foreground "#e0bf90" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#eb9366"))))
 '(font-lock-type-face ((t (:foreground "#99ee99" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#f0dfaf"))))
 '(font-lock-warning-face ((t (:background "#332323" :foreground "#e37170"))))
 '(fringe ((t (:background "grey20"))))
 '(widget-button ((t (:background "#92b6f4" :foreground "black" :box (:line-width 2 :color "#92b6f4" :style released-button) :weight bold))))
 '(widget-button-pressed ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style pressed-button)))))
 '(widget-field ((t (:background "#333333"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "#333333"))))
 '(vertical-border ((t nil)))
 '(variable-pitch ((t (:family "Ubuntu"))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(show-paren-match ((t (:background "#b2a6f4" :foreground "#000000" :weight extra-bold))))
 '(trailing-whitespace ((t (:background "firebrick"))))
 '(secondary-selection ((t (:background "#334433"))))
 '(next-error ((t (:background "#441133"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style released-button) :weight light))))
 '(mode-line-highlight ((t (:background "#a47bff" :foreground "black" :box (:line-width 2 :color "#a47bff" :style released-button)))))
 '(mode-line-emphasis ((t (:foreground "#c460ff" :weight bold))))
 '(mode-line-buffer-id ((t (:foreground "#30ddff" :weight normal))))
 '(mode-line ((t (:background "#131313" :foreground "#a47bff" :box (:line-width -1 :color "#5276b4")))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(menu ((t nil)))
 '(match ((t (:background "#3344bb"))))
 '(link-visited ((t (:foreground "violet" :underline t))))
 '(link ((t (:foreground "cyan1" :underline t))))
 '(lazy-highlight ((t (:background "#335544"))))
 '(italic ((t (:slant italic))))
 '(isearch-fail ((t (:background "red4"))))
 '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
 '(ido-subdir ((t (:foreground "red1"))))
 '(ido-only-match ((t (:foreground "ForestGreen"))))
 '(ido-first-match ((t (:weight bold))))
 '(highlight ((t (:background "#115544"))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box (:line-width -1 :color "#5276b4")))))
 '(fixed-pitch ((t (:family "Terminus"))))
 '(cursor ((t nil))))

(provide-theme 'pdklburn)
